### PR TITLE
Fix session cleanup

### PR DESCRIPTION
**Pull request by dizlexik**
My sessions were being deleted every time the cleanup would run.
This fixes the bug.

### CODE REVIEW

**Comment by multimeric** [comment]
Judging from this PR, you set your cleanupTime in seconds, but the documentation says it's in milliseconds. I think the problem may be on your side here?

https://github.com/TMiguelT/koa-pg-session#options

**Comment by dizlexik** [comment]
This issue doesn't pertain to cleanupTime, which btw I didn't set and just left as the default. The issue is that `cleanupSql` is executing the SQL statement `DELETE FROM %I.%I WHERE expiry <= to_timestamp($1);` with a value of `Date.now()`, which ends up being some time far in the future. If you look at line 112 you'll see the same `/ 1000` logic being applied to a `Date.now()` before being used in a SQL statement.

The issue is that `to_timestamp` requires seconds and not milliseconds.
http://www.postgresql.org/docs/current/static/functions-formatting.html

Without this fix the cleanup routine will always end up deleting all session rows in the database.

**Comment by multimeric** [comment]
Okay I understand now. I'm a bit busy but could you write a test for this
with the PR and I'll merge it

**Comment by dizlexik** [comment]
Updated tests.

The `should still exist before the expiry time has passed` and `should persist data between sessions` tests failed pre-fix and pass post-fix.

**Comment by dizlexik** [comment]
Hey @TMiguelT, thanks for merging this. What are your plans on publishing a new release of this to npm? This feels like a fairly major bug since this is such a small module.

**Comment by multimeric** [comment]
I'll try to find time to do this. I still haven't tested it myself which I
feel I should do before publishing. In the meantime if you need to use this
through npm you can use the git url as opposed to just the package name and
it should use this merged version.
On 11/05/2016 2:41 AM, "Joe Lutz" notifications@github.com wrote:

Hey @TMiguelT https://github.com/TMiguelT, thanks for merging this. What
are your plans on publishing a new release of this to npm? This feels like
a fairly major bug since this is such a small module.

**Comment by dizlexik** [comment]
Thanks. I have the patched version loaded up in my private npm so I'm good. I was more worried about everyone else using this and constantly losing sessions. I hope you can find the time to review and run the updated tests soon.

**Comment by dizlexik** [comment]
Hey just a friendly reminder that this bug is still plaguing everyone currently relying on this module to provide sessions that last longer than 45 minutes.

**Pull request merged**
